# Generated by Django 4.2 on 2023-04-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='area',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='length',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='width',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
